spring:
  datasource:
    url: jdbc:mysql://localhost:3306/timestamp?useSSL=false&allowPublicKeyRetrieval=true
    username: timestamp
    password: timestamp
    driver: com.mysql.cj.jdbc.Driver

slack:
  enabled: false
  webhook-url:
